### PR TITLE
Add accessibility API support to Dragonfly. 

### PR DESCRIPTION
**Pull request by wolfmanstout**
Currently only Windows is supported, but the design supports multiple operating systems and APIs. This enables text selection and editing more powerful than what Dragon provides natively, to a wider range of applications (notably Chrome and Firefox).

### CODE REVIEW

**Comment by wolfmanstout** [comment]
Here are examples of this API in action in my grammar:
Grammar: https://github.com/wolfmanstout/dragonfly-commands/blob/master/_repeat.py#L443
Element construction: https://github.com/wolfmanstout/dragonfly-commands/blob/master/_repeat.py#L636

**Comment by Danesprite** [comment]
Thanks again for this! I'll test this and let you know if I find any issues with it.

**Comment by wolfmanstout** [comment]
Made a few minor improvements since I originally posted it.

I'm wondering if maybe I should add something to the README that mentions that this is in Beta. I suspect I may want to make (breaking) changes to the API as I continue to work on this. I will try to avoid that, but maybe best to warn folks just in case? I am hoping to get this into the mainline release, though, so that people can start benefiting from these very practically useful features (and so that I can blog about it and point people to `pip install dragonfly2`.

**Comment by LexiconCode** [comment]
I would be in favor of that plan but it's up to Danesprite.

**Comment by wolfmanstout** [comment]
Also, I'm still working on my blog post, so no pressure time-wise. Will be done next weekend at the earliest.

**Comment by calmofthestorm** [comment]
This is really exciting! I never considered the possibility of taking this approach (vs just emulating keyboard and mouse), and this really opens a lot of doors!

**Comment by Danesprite** [comment]
That sounds good to me. I think an `accessibility.txt` file in `documentation/` would also be good, at least to generate documentation from files under dragonfly.accessibility. That can be done later though of course.

I have tried testing this, but ran into a few problems. Unless I'm mistaken, [pyia2/setup.py](https://github.com/jongund/pyia2/blob/master/setup.py) needs to be changed to import pyia2 instead of pyia. I followed the instructions in the README after fixing that, but ended up with the following error shortly after I started speaking:
```
 Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\Lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\Lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\Dane\AppData\Roaming\Python\Python27\site-packages\dragonfly\accessibility\ia2.py", line 74, in _start_blocking
    import pyia2
  File "C:\Python27\lib\site-packages\pyia2\__init__.py", line 32, in <module>
    import accessible
  File "C:\Python27\lib\site-packages\pyia2\accessible.py", line 32, in <module>
    IAccessible2 = GetModule('ia2.tlb')
  File "C:\Python27\lib\site-packages\comtypes\client\_generate.py", line 95, in GetModule
    tlib = comtypes.typeinfo.LoadTypeLibEx(tlib)
  File "C:\Python27\lib\site-packages\comtypes\typeinfo.py", line 485, in LoadTypeLibEx
    _oleaut32.LoadTypeLibEx(c_wchar_p(szFile), regkind, byref(ptl))
  File "_ctypes/callproc.c", line 950, in GetResult
WindowsError: [Error -2147312566] Error loading type library/DLL
```

Have you run into this problem before? I did run `regsvr32 IAccessible2Proxy.dll` successfully on the DLL from the pyia2 repo.

**Comment by wolfmanstout** [comment]
I was using PYTHONPATH to point to my local repository, so that's why I didn't hit the problems you saw. I can look into fixing those so this can be "pip -e" installed, which is cleaner. Seems like the maintainer is pretty open to pull requests.

On the COMErrors, it was useful during development having these issues propagate up, but I can catch them and use logging instead.

**Comment by Danesprite** [comment]
Ah right, that explains it. Sounds good to me. I think it needs to use setuptools instead of distutils for that to work. That's good to hear!

Alright then. I'd say just leave it as it is if they are useful to you.

**Comment by Danesprite** [comment]
I'm happy to merge this now if you want. I'm planning to release version 0.10.0 soon.

**Comment by wolfmanstout** [comment]
Okay, this is ready to go. Made some more improvements and overhauled the documentation to properly use Sphinx (and removed the reference from the readme, which would be redundant).

**Comment by Danesprite** [comment]
No problem. Sure, I'll do that :-)

**Pull request merged**
