### PR TITLE
Added scrolling support to Mouse action.

### PR DESCRIPTION
**Pull request by wolfmanstout**
Reviving this pull request that never went through:
https://github.com/t4ngo/dragonfly/pull/59

This is actually really useful! If you combine this with eye tracking-based mouse movements, it's very easy to create commands which scroll wherever you are looking. That won't work with keypresses without clicking, which cannot be safely done anywhere.

### CODE REVIEW

**Comment by wolfmanstout** [comment]
I remember when I first implemented this I tried adding horizontal scrolling support and it just didn’t work in practice. I can give it another stab.

**Comment by Danesprite** [comment]
Ah okay. I'm not very familiar with Windows GUI programming, would applications have to specifically support horizontal scrolling for it to work? We can always just add that later on.

**Comment by Versatilus** [comment]
My implementation of horizontal mouse input works for me. I'm able to scroll various Windows applications horizontally, such as scrolling the video list on the Netflix website and scrolling multiple text editors. Some applications (such as Netflix on Chrome) are sensitive to the actual delta values and only respond to multiples of 120, while others seem to trigger off of the number of update calls (Emacs comes to mind).

I seem to get a better response out of using a brief pause, approximately 10 to 100 ms, between mouse wheel events instead of rapidly triggering events.

I can also confirm that, with heavy filtering, controlling the mouse pointer using eye tracking can be very effective!

**Comment by Danesprite** [comment]
Thanks for the explanation! It looks like we might want to merge that instead. I notice you also add extra mouse buttons. You can make a pull request to this fork if you like.

@wolfmanstout Does this work for you?

**Comment by wolfmanstout** [comment]
Sure. I like that @Versatilus achieved this with less code. The only minor advantages I see to my implementation is that it allows the user to directly specify a larger scrolling amount instead of achieving this with multiple events.  This may be a non-advantage, though, because it sounds like support for this may be weak. Also, it gives control over parsing so we can disallow “down” and “up”, which don’t make sense here. If we want these features then I can merge in the extra buttons etc on the weekend. I’m fine with just dropping this though.

**Comment by Danesprite** [comment]
Alright then. I'd say let's merge @Versatilus' version and disallow "down" and "up" by modifying `_process_button` to check for "wheel" or "step". I think that should work. As you say, the support for larger scrolling amounts seems a bit weak.

**Comment by wolfmanstout** [comment]
Sounds good to me. I will close this out once @Versatilus has committed his pull request.

**Comment by Versatilus** [comment]
I don't know when I'll actually get to this, so you have my permission to do whatever you want with my code.

**Comment by Danesprite** [comment]
@Versatilus No problem. I'll make another pull request for your version and merge it.

@wolfmanstout It looks like this started conflicting because of the switch from CRLF to LF (ed9745cc). Correct me if I'm wrong, but I don't think that should be an issue for changes introduced after that commit.

**Comment by wolfmanstout** [comment]
@Danesprite I would expect conflicts for old changes. Here's how I was able to merge your line ending change and fix my branches on my fork:

My master branch directly tracks your master branch; no local changes.
```
git checkout master
git fetch upstream
git merge upstream/master
```

Here is how I fixed a branch with local changes. This will merge in the changes while ignoring whitespace issues and hence avoiding conflicts:
`git merge master -s recursive -Xignore-space-at-eol`

This should go pretty smoothly, except there may be some minor conflicts due to deleted files. You can resolve these with git mergetool, always taking the remote/deleted file.
`git mergetool`

Next, you need to fix your local changes so that they don't attempt to rewrite line endings. Just follow this GitHub guide verbatim: https://help.github.com/articles/dealing-with-line-endings/#refreshing-a-repository-after-changing-line-endings

FYI I'm expecting to abandon this pull request once you've merged in @Versatilus changes. But hopefully this helps you deal with conflicts there (and same for anyone else dealing with problems). This will go much more easily for anything branched after your change!

**Comment by Danesprite** [comment]
Thanks for the detailed explanation and clarification. I didn't know about that useful option for `git merge`. I notice it also exists for `git diff` as `--ignore-space-at-eol`. I'll merge those changes soon.

**Pull request closed without merging**
