### PR TITLE
Hotfix release 0.10.1

### PR DESCRIPTION
**Pull request by Danesprite**
This is to fix the backwards-incompatible changes mentioned in Danesprite/dragonfly#51.

At the moment this requires manually deleting/modifying the config file.

@Versatilus @Wolfmanstout @caspark Let me know if this fix is acceptable. If so, I'll merge this branch, tag the commit and upload to PyPI.

### CODE REVIEW

**Comment by Danesprite** [comment]
I've added some documentation for the changes to `Text`. Let me know what you think.

I've changed the default value for `use_hardware` back to what it was because it makes more sense given the `hardware_apps` setting.

**Comment by Versatilus** [comment]
This looks good to me.

**Comment by wolfmanstout** [comment]
Thanks, this looks good to me. I think this is a good call.

**Comment by Danesprite** [comment]
I merged/squashed this locally. All done and released.

**Pull request closed without merging**
